export const ALL_CHEMICAL_REQUEST = "ALL_CHEMICAL_REQUEST";
export const ALL_CHEMICAL_SUCCESS = "ALL_CHEMICAL_SUCCESS";
export const ALL_CHEMICAL_FAIL = "ALL_CHEMICAL_FAIL";

export const ADMIN_CHEMICAL_REQUEST = "ADMIN_CHEMICAL_REQUEST";
export const ADMIN_CHEMICAL_SUCCESS = "ADMIN_CHEMICAL_SUCCESS";
export const ADMIN_CHEMICAL_FAIL = "ADMIN_CHEMICAL_FAIL";

export const CHEMICALS_BY_DRUG_CATEGORY_REQUEST = "CHEMICALS_BY_DRUG_CATEGORY_REQUEST";
export const CHEMICALS_BY_DRUG_CATEGORY_SUCCESS = "CHEMICALS_BY_DRUG_CATEGORY_SUCCESS";
export const CHEMICALS_BY_DRUG_CATEGORY_FAIL = "CHEMICALS_BY_DRUG_CATEGORY_FAIL";

export const NEW_CHEMICAL_REQUEST = "NEW_CHEMICAL_REQUEST";
export const NEW_CHEMICAL_SUCCESS = "NEW_CHEMICAL_SUCCESS";
export const NEW_CHEMICAL_RESET = "NEW_CHEMICAL_RESET";
export const NEW_CHEMICAL_FAIL = "NEW_CHEMICAL_FAIL";

export const UPDATE_CHEMICAL_REQUEST = "UPDATE_CHEMICAL_REQUEST";
export const UPDATE_CHEMICAL_SUCCESS = "UPDATE_CHEMICAL_SUCCESS";
export const UPDATE_CHEMICAL_RESET = "UPDATE_CHEMICAL_RESET";
export const UPDATE_CHEMICAL_FAIL = "UPDATE_CHEMICAL_FAIL";

export const DELETE_CHEMICAL_REQUEST = "DELETE_CHEMICAL_REQUEST";
export const DELETE_CHEMICAL_SUCCESS = "DELETE_CHEMICAL_SUCCESS";
export const DELETE_CHEMICAL_RESET = "DELETE_CHEMICAL_RESET";
export const DELETE_CHEMICAL_FAIL = "DELETE_CHEMICAL_FAIL";

export const CHEMICAL_DETAILS_REQUEST = "CHEMICAL_DETAILS_REQUEST";
export const CHEMICAL_DETAILS_SUCCESS = "CHEMICAL_DETAILS_SUCCESS";
export const CHEMICAL_DETAILS_FAIL = "CHEMICAL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
