export const ALL_DRUG_PRICE_REQUEST = "ALL_DRUG_PRICE_REQUEST";
export const ALL_DRUG_PRICE_SUCCESS = "ALL_DRUG_PRICE_SUCCESS";
export const ALL_DRUG_PRICE_FAIL = "ALL_DRUG_PRICE_FAIL";

export const ADMIN_DRUG_PRICE_REQUEST = "ADMIN_DRUG_PRICE_REQUEST";
export const ADMIN_DRUG_PRICE_SUCCESS = "ADMIN_DRUG_PRICE_SUCCESS";
export const ADMIN_DRUG_PRICE_FAIL = "ADMIN_DRUG_PRICE_FAIL";

export const NEW_DRUG_PRICE_REQUEST = "NEW_DRUG_PRICE_REQUEST";
export const NEW_DRUG_PRICE_SUCCESS = "NEW_DRUG_PRICE_SUCCESS";
export const NEW_DRUG_PRICE_RESET = "NEW_DRUG_PRICE_RESET";
export const NEW_DRUG_PRICE_FAIL = "NEW_DRUG_PRICE_FAIL";

export const UPDATE_DRUG_PRICE_REQUEST = "UPDATE_DRUG_PRICE_REQUEST";
export const UPDATE_DRUG_PRICE_SUCCESS = "UPDATE_DRUG_PRICE_SUCCESS";
export const UPDATE_DRUG_PRICE_RESET = "UPDATE_DRUG_PRICE_RESET";
export const UPDATE_DRUG_PRICE_FAIL = "UPDATE_DRUG_PRICE_FAIL";

export const UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_REQUEST =
  "UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_REQUEST";
export const UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_SUCCESS =
  "UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_SUCCESS";
export const UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_RESET =
  "UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_RESET";
export const UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_FAIL =
  "UPDATE_DRUG_PRICE_BY_DRUG_ZONE_ID_FAIL";

export const DELETE_DRUG_PRICE_REQUEST = "DELETE_DRUG_PRICE_REQUEST";
export const DELETE_DRUG_PRICE_SUCCESS = "DELETE_DRUG_PRICE_SUCCESS";
export const DELETE_DRUG_PRICE_RESET = "DELETE_DRUG_PRICE_RESET";
export const DELETE_DRUG_PRICE_FAIL = "DELETE_DRUG_PRICE_FAIL";

export const DRUG_PRICE_DETAILS_REQUEST = "DRUG_PRICE_DETAILS_REQUEST";
export const DRUG_PRICE_DETAILS_SUCCESS = "DRUG_PRICE_DETAILS_SUCCESS";
export const DRUG_PRICE_DETAILS_FAIL = "DRUG_PRICE_DETAILS_FAIL";

export const DRUG_PRICE_DETAILS_BY_ZONE_ID_REQUEST =
  "DRUG_PRICE_DETAILS_BY_ZONE_ID_REQUEST";
export const DRUG_PRICE_DETAILS_BY_ZONE_ID_SUCCESS =
  "DRUG_PRICE_DETAILS_BY_ZONE_ID_SUCCESS";
export const DRUG_PRICE_DETAILS_BY_ZONE_ID_FAIL =
  "DRUG_PRICE_DETAILS_BY_ZONE_ID_FAIL";

export const DRUG_PRICE_DETAILS_BY_DRUG_ID_REQUEST =
  "DRUG_PRICE_DETAILS_BY_DRUG_ID_REQUEST";
export const DRUG_PRICE_DETAILS_BY_DRUG_ID_SUCCESS =
  "DRUG_PRICE_DETAILS_BY_DRUG_ID_SUCCESS";
export const DRUG_PRICE_DETAILS_BY_DRUG_ID_FAIL =
  "DRUG_PRICE_DETAILS_BY_DRUG_ID_FAIL";

export const DRUG_PRICE_DETAILS_BY_DRUG_ZONE_ID_REQUEST =
  "DRUG_PRICE_DETAILS_BY_DRUG_ZONE_ID_REQUEST";
export const DRUG_PRICE_DETAILS_BY_DRUG_ZONE_ID_SUCCESS =
  "DRUG_PRICE_DETAILS_BY_DRUG_ZONE_ID_SUCCESS";
export const DRUG_PRICE_DETAILS_BY_DRUG_ZONE_ID_FAIL =
  "DRUG_PRICE_DETAILS_BY_DRUG_ZONE_ID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
