export const ALL_PIN_AMOUNT_REQUEST = "ALL_PIN_AMOUNT_REQUEST";
export const ALL_PIN_AMOUNT_SUCCESS = "ALL_PIN_AMOUNT_SUCCESS";
export const ALL_PIN_AMOUNT_FAIL = "ALL_PIN_AMOUNT_FAIL";

export const ADMIN_PIN_AMOUNT_REQUEST = "ADMIN_PIN_AMOUNT_REQUEST";
export const ADMIN_PIN_AMOUNT_SUCCESS = "ADMIN_PIN_AMOUNT_SUCCESS";
export const ADMIN_PIN_AMOUNT_FAIL = "ADMIN_PIN_AMOUNT_FAIL";

export const NEW_PIN_AMOUNT_REQUEST = "NEW_PIN_AMOUNT_REQUEST";
export const NEW_PIN_AMOUNT_SUCCESS = "NEW_PIN_AMOUNT_SUCCESS";
export const NEW_PIN_AMOUNT_RESET = "NEW_PIN_AMOUNT_RESET";
export const NEW_PIN_AMOUNT_FAIL = "NEW_PIN_AMOUNT_FAIL";

export const UPDATE_PIN_AMOUNT_REQUEST = "UPDATE_PIN_AMOUNT_REQUEST";
export const UPDATE_PIN_AMOUNT_SUCCESS = "UPDATE_PIN_AMOUNT_SUCCESS";
export const UPDATE_PIN_AMOUNT_RESET = "UPDATE_PIN_AMOUNT_RESET";
export const UPDATE_PIN_AMOUNT_FAIL = "UPDATE_PIN_AMOUNT_FAIL";

export const DELETE_PIN_AMOUNT_REQUEST = "DELETE_PIN_AMOUNT_REQUEST";
export const DELETE_PIN_AMOUNT_SUCCESS = "DELETE_PIN_AMOUNT_SUCCESS";
export const DELETE_PIN_AMOUNT_RESET = "DELETE_PIN_AMOUNT_RESET";
export const DELETE_PIN_AMOUNT_FAIL = "DELETE_PIN_AMOUNT_FAIL";

export const PIN_AMOUNT_DETAILS_REQUEST = "PIN_AMOUNT_DETAILS_REQUEST";
export const PIN_AMOUNT_DETAILS_SUCCESS = "PIN_AMOUNT_DETAILS_SUCCESS";
export const PIN_AMOUNT_DETAILS_FAIL = "PIN_AMOUNT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
