export const ALL_PRODUCT_CATEGORY_REQUEST = "ALL_PRODUCT_CATEGORY_REQUEST";
export const ALL_PRODUCT_CATEGORY_SUCCESS = "ALL_PRODUCT_CATEGORY_SUCCESS";
export const ALL_PRODUCT_CATEGORY_FAIL = "ALL_PRODUCT_CATEGORY_FAIL";

export const ADMIN_PRODUCT_CATEGORY_REQUEST = "ADMIN_PRODUCT_CATEGORY_REQUEST";
export const ADMIN_PRODUCT_CATEGORY_SUCCESS = "ADMIN_PRODUCT_CATEGORY_SUCCESS";
export const ADMIN_PRODUCT_CATEGORY_FAIL = "ADMIN_PRODUCT_CATEGORY_FAIL";

export const NEW_PRODUCT_CATEGORY_REQUEST = "NEW_PRODUCT_CATEGORY_REQUEST";
export const NEW_PRODUCT_CATEGORY_SUCCESS = "NEW_PRODUCT_CATEGORY_SUCCESS";
export const NEW_PRODUCT_CATEGORY_RESET = "NEW_PRODUCT_CATEGORY_RESET";
export const NEW_PRODUCT_CATEGORY_FAIL = "NEW_PRODUCT_CATEGORY_FAIL";

export const UPDATE_PRODUCT_CATEGORY_REQUEST = "UPDATE_PRODUCT_CATEGORY_REQUEST";
export const UPDATE_PRODUCT_CATEGORY_SUCCESS = "UPDATE_PRODUCT_CATEGORY_SUCCESS";
export const UPDATE_PRODUCT_CATEGORY_RESET = "UPDATE_PRODUCT_CATEGORY_RESET";
export const UPDATE_PRODUCT_CATEGORY_FAIL = "UPDATE_PRODUCT_CATEGORY_FAIL";

export const DELETE_PRODUCT_CATEGORY_REQUEST = "DELETE_PRODUCT_CATEGORY_REQUEST";
export const DELETE_PRODUCT_CATEGORY_SUCCESS = "DELETE_PRODUCT_CATEGORY_SUCCESS";
export const DELETE_PRODUCT_CATEGORY_RESET = "DELETE_PRODUCT_CATEGORY_RESET";
export const DELETE_PRODUCT_CATEGORY_FAIL = "DELETE_PRODUCT_CATEGORY_FAIL";

export const PRODUCT_CATEGORY_DETAILS_REQUEST = "PRODUCT_CATEGORY_DETAILS_REQUEST";
export const PRODUCT_CATEGORY_DETAILS_SUCCESS = "PRODUCT_CATEGORY_DETAILS_SUCCESS";
export const PRODUCT_CATEGORY_DETAILS_FAIL = "PRODUCT_CATEGORY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
