export const ALL_PRODUCT_PRICE_REQUEST = "ALL_PRODUCT_PRICE_REQUEST";
export const ALL_PRODUCT_PRICE_SUCCESS = "ALL_PRODUCT_PRICE_SUCCESS";
export const ALL_PRODUCT_PRICE_FAIL = "ALL_PRODUCT_PRICE_FAIL";

export const ADMIN_PRODUCT_PRICE_REQUEST = "ADMIN_PRODUCT_PRICE_REQUEST";
export const ADMIN_PRODUCT_PRICE_SUCCESS = "ADMIN_PRODUCT_PRICE_SUCCESS";
export const ADMIN_PRODUCT_PRICE_FAIL = "ADMIN_PRODUCT_PRICE_FAIL";

export const NEW_PRODUCT_PRICE_REQUEST = "NEW_PRODUCT_PRICE_REQUEST";
export const NEW_PRODUCT_PRICE_SUCCESS = "NEW_PRODUCT_PRICE_SUCCESS";
export const NEW_PRODUCT_PRICE_RESET = "NEW_PRODUCT_PRICE_RESET";
export const NEW_PRODUCT_PRICE_FAIL = "NEW_PRODUCT_PRICE_FAIL";

export const UPDATE_PRODUCT_PRICE_REQUEST = "UPDATE_PRODUCT_PRICE_REQUEST";
export const UPDATE_PRODUCT_PRICE_SUCCESS = "UPDATE_PRODUCT_PRICE_SUCCESS";
export const UPDATE_PRODUCT_PRICE_RESET = "UPDATE_PRODUCT_PRICE_RESET";
export const UPDATE_PRODUCT_PRICE_FAIL = "UPDATE_PRODUCT_PRICE_FAIL";

export const UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_REQUEST =
  "UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_REQUEST";
export const UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_SUCCESS =
  "UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_SUCCESS";
export const UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_RESET =
  "UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_RESET";
export const UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_FAIL =
  "UPDATE_PRODUCT_PRICE_BY_PRODUCT_ZONE_ID_FAIL";

export const DELETE_PRODUCT_PRICE_REQUEST = "DELETE_PRODUCT_PRICE_REQUEST";
export const DELETE_PRODUCT_PRICE_SUCCESS = "DELETE_PRODUCT_PRICE_SUCCESS";
export const DELETE_PRODUCT_PRICE_RESET = "DELETE_PRODUCT_PRICE_RESET";
export const DELETE_PRODUCT_PRICE_FAIL = "DELETE_PRODUCT_PRICE_FAIL";

export const PRODUCT_PRICE_DETAILS_REQUEST = "PRODUCT_PRICE_DETAILS_REQUEST";
export const PRODUCT_PRICE_DETAILS_SUCCESS = "PRODUCT_PRICE_DETAILS_SUCCESS";
export const PRODUCT_PRICE_DETAILS_FAIL = "PRODUCT_PRICE_DETAILS_FAIL";

export const PRODUCT_PRICE_DETAILS_BY_ZONE_ID_REQUEST =
  "PRODUCT_PRICE_DETAILS_BY_ZONE_ID_REQUEST";
export const PRODUCT_PRICE_DETAILS_BY_ZONE_ID_SUCCESS =
  "PRODUCT_PRICE_DETAILS_BY_ZONE_ID_SUCCESS";
export const PRODUCT_PRICE_DETAILS_BY_ZONE_ID_FAIL =
  "PRODUCT_PRICE_DETAILS_BY_ZONE_ID_FAIL";

export const PRODUCT_PRICE_DETAILS_BY_PRODUCT_ID_REQUEST =
  "PRODUCT_PRICE_DETAILS_BY_PRODUCT_ID_REQUEST";
export const PRODUCT_PRICE_DETAILS_BY_PRODUCT_ID_SUCCESS =
  "PRODUCT_PRICE_DETAILS_BY_PRODUCT_ID_SUCCESS";
export const PRODUCT_PRICE_DETAILS_BY_PRODUCT_ID_FAIL =
  "PRODUCT_PRICE_DETAILS_BY_PRODUCT_ID_FAIL";

  export const PRODUCT_PRICE_DETAILS_BY_PRODUCT_ZONE_ID_REQUEST =
    "PRODUCT_PRICE_DETAILS_BY_PRODUCT_ZONE_ID_REQUEST";
  export const PRODUCT_PRICE_DETAILS_BY_PRODUCT_ZONE_ID_SUCCESS =
    "PRODUCT_PRICE_DETAILS_BY_PRODUCT_ZONE_ID_SUCCESS";
  export const PRODUCT_PRICE_DETAILS_BY_PRODUCT_ZONE_ID_FAIL =
    "PRODUCT_PRICE_DETAILS_BY_PRODUCT_ZONE_ID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
