export const ALL_ZONE_REQUEST = "ALL_ZONE_REQUEST";
export const ALL_ZONE_SUCCESS = "ALL_ZONE_SUCCESS";
export const ALL_ZONE_FAIL = "ALL_ZONE_FAIL";

export const ADMIN_ZONE_REQUEST = "ADMIN_ZONE_REQUEST";
export const ADMIN_ZONE_SUCCESS = "ADMIN_ZONE_SUCCESS";
export const ADMIN_ZONE_FAIL = "ADMIN_ZONE_FAIL";

export const NEW_ZONE_REQUEST = "NEW_ZONE_REQUEST";
export const NEW_ZONE_SUCCESS = "NEW_ZONE_SUCCESS";
export const NEW_ZONE_RESET = "NEW_ZONE_RESET";
export const NEW_ZONE_FAIL = "NEW_ZONE_FAIL";

export const UPDATE_ZONE_REQUEST = "UPDATE_ZONE_REQUEST";
export const UPDATE_ZONE_SUCCESS = "UPDATE_ZONE_SUCCESS";
export const UPDATE_ZONE_RESET = "UPDATE_ZONE_RESET";
export const UPDATE_ZONE_FAIL = "UPDATE_ZONE_FAIL";

export const DELETE_ZONE_REQUEST = "DELETE_ZONE_REQUEST";
export const DELETE_ZONE_SUCCESS = "DELETE_ZONE_SUCCESS";
export const DELETE_ZONE_RESET = "DELETE_ZONE_RESET";
export const DELETE_ZONE_FAIL = "DELETE_ZONE_FAIL";

export const ZONE_DETAILS_REQUEST = "ZONE_DETAILS_REQUEST";
export const ZONE_DETAILS_SUCCESS = "ZONE_DETAILS_SUCCESS";
export const ZONE_DETAILS_FAIL = "ZONE_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
