export const ALL_DEVICE_PRICE_REQUEST = "ALL_DEVICE_PRICE_REQUEST";
export const ALL_DEVICE_PRICE_SUCCESS = "ALL_DEVICE_PRICE_SUCCESS";
export const ALL_DEVICE_PRICE_FAIL = "ALL_DEVICE_PRICE_FAIL";

export const ADMIN_DEVICE_PRICE_REQUEST = "ADMIN_DEVICE_PRICE_REQUEST";
export const ADMIN_DEVICE_PRICE_SUCCESS = "ADMIN_DEVICE_PRICE_SUCCESS";
export const ADMIN_DEVICE_PRICE_FAIL = "ADMIN_DEVICE_PRICE_FAIL";

export const NEW_DEVICE_PRICE_REQUEST = "NEW_DEVICE_PRICE_REQUEST";
export const NEW_DEVICE_PRICE_SUCCESS = "NEW_DEVICE_PRICE_SUCCESS";
export const NEW_DEVICE_PRICE_RESET = "NEW_DEVICE_PRICE_RESET";
export const NEW_DEVICE_PRICE_FAIL = "NEW_DEVICE_PRICE_FAIL";

export const UPDATE_DEVICE_PRICE_REQUEST = "UPDATE_DEVICE_PRICE_REQUEST";
export const UPDATE_DEVICE_PRICE_SUCCESS = "UPDATE_DEVICE_PRICE_SUCCESS";
export const UPDATE_DEVICE_PRICE_RESET = "UPDATE_DEVICE_PRICE_RESET";
export const UPDATE_DEVICE_PRICE_FAIL = "UPDATE_DEVICE_PRICE_FAIL";

export const DELETE_DEVICE_PRICE_REQUEST = "DELETE_DEVICE_PRICE_REQUEST";
export const DELETE_DEVICE_PRICE_SUCCESS = "DELETE_DEVICE_PRICE_SUCCESS";
export const DELETE_DEVICE_PRICE_RESET = "DELETE_DEVICE_PRICE_RESET";
export const DELETE_DEVICE_PRICE_FAIL = "DELETE_DEVICE_PRICE_FAIL";

export const DEVICE_PRICE_DETAILS_REQUEST = "DEVICE_PRICE_DETAILS_REQUEST";
export const DEVICE_PRICE_DETAILS_SUCCESS = "DEVICE_PRICE_DETAILS_SUCCESS";
export const DEVICE_PRICE_DETAILS_FAIL = "DEVICE_PRICE_DETAILS_FAIL";

export const DEVICE_PRICE_DETAILS_BY_ZONE_ID_REQUEST =
  "DEVICE_PRICE_DETAILS_BY_ZONE_ID_REQUEST";
export const DEVICE_PRICE_DETAILS_BY_ZONE_ID_SUCCESS =
  "DEVICE_PRICE_DETAILS_BY_ZONE_ID_SUCCESS";
export const DEVICE_PRICE_DETAILS_BY_ZONE_ID_FAIL =
  "DEVICE_PRICE_DETAILS_BY_ZONE_ID_FAIL";

export const DEVICE_PRICE_DETAILS_BY_DEVICE_ID_REQUEST =
  "DEVICE_PRICE_DETAILS_BY_DEVICE_ID_REQUEST";
export const DEVICE_PRICE_DETAILS_BY_DEVICE_ID_SUCCESS =
  "DEVICE_PRICE_DETAILS_BY_DEVICE_ID_SUCCESS";
export const DEVICE_PRICE_DETAILS_BY_DEVICE_ID_FAIL =
  "DEVICE_PRICE_DETAILS_BY_DEVICE_ID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
