export const ALL_DEVICE_CATEGORY_REQUEST = "ALL_DEVICE_CATEGORY_REQUEST";
export const ALL_DEVICE_CATEGORY_SUCCESS = "ALL_DEVICE_CATEGORY_SUCCESS";
export const ALL_DEVICE_CATEGORY_FAIL = "ALL_DEVICE_CATEGORY_FAIL";

export const ADMIN_DEVICE_CATEGORY_REQUEST = "ADMIN_DEVICE_CATEGORY_REQUEST";
export const ADMIN_DEVICE_CATEGORY_SUCCESS = "ADMIN_DEVICE_CATEGORY_SUCCESS";
export const ADMIN_DEVICE_CATEGORY_FAIL = "ADMIN_DEVICE_CATEGORY_FAIL";

export const NEW_DEVICE_CATEGORY_REQUEST = "NEW_DEVICE_CATEGORY_REQUEST";
export const NEW_DEVICE_CATEGORY_SUCCESS = "NEW_DEVICE_CATEGORY_SUCCESS";
export const NEW_DEVICE_CATEGORY_RESET = "NEW_DEVICE_CATEGORY_RESET";
export const NEW_DEVICE_CATEGORY_FAIL = "NEW_DEVICE_CATEGORY_FAIL";

export const UPDATE_DEVICE_CATEGORY_REQUEST =
  "UPDATE_DEVICE_CATEGORY_REQUEST";
export const UPDATE_DEVICE_CATEGORY_SUCCESS =
  "UPDATE_DEVICE_CATEGORY_SUCCESS";
export const UPDATE_DEVICE_CATEGORY_RESET = "UPDATE_DEVICE_CATEGORY_RESET";
export const UPDATE_DEVICE_CATEGORY_FAIL = "UPDATE_DEVICE_CATEGORY_FAIL";

export const DELETE_DEVICE_CATEGORY_REQUEST =
  "DELETE_DEVICE_CATEGORY_REQUEST";
export const DELETE_DEVICE_CATEGORY_SUCCESS =
  "DELETE_DEVICE_CATEGORY_SUCCESS";
export const DELETE_DEVICE_CATEGORY_RESET = "DELETE_DEVICE_CATEGORY_RESET";
export const DELETE_DEVICE_CATEGORY_FAIL = "DELETE_DEVICE_CATEGORY_FAIL";

export const DEVICE_CATEGORY_DETAILS_REQUEST =
  "DEVICE_CATEGORY_DETAILS_REQUEST";
export const DEVICE_CATEGORY_DETAILS_SUCCESS =
  "DEVICE_CATEGORY_DETAILS_SUCCESS";
export const DEVICE_CATEGORY_DETAILS_FAIL = "DEVICE_CATEGORY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
