export const ALL_DEVICE_REQUEST = "ALL_DEVICE_REQUEST";
export const ALL_DEVICE_SUCCESS = "ALL_DEVICE_SUCCESS";
export const ALL_DEVICE_FAIL = "ALL_DEVICE_FAIL";

export const ADMIN_DEVICE_REQUEST = "ADMIN_DEVICE_REQUEST";
export const ADMIN_DEVICE_SUCCESS = "ADMIN_DEVICE_SUCCESS";
export const ADMIN_DEVICE_FAIL = "ADMIN_DEVICE_FAIL";

export const NEW_DEVICE_REQUEST = "NEW_DEVICE_REQUEST";
export const NEW_DEVICE_SUCCESS = "NEW_DEVICE_SUCCESS";
export const NEW_DEVICE_RESET = "NEW_DEVICE_RESET";
export const NEW_DEVICE_FAIL = "NEW_DEVICE_FAIL";

export const UPDATE_DEVICE_REQUEST = "UPDATE_DEVICE_REQUEST";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_RESET = "UPDATE_DEVICE_RESET";
export const UPDATE_DEVICE_FAIL = "UPDATE_DEVICE_FAIL";

export const DELETE_DEVICE_REQUEST = "DELETE_DEVICE_REQUEST";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";
export const DELETE_DEVICE_RESET = "DELETE_DEVICE_RESET";
export const DELETE_DEVICE_FAIL = "DELETE_DEVICE_FAIL";

export const DEVICE_DETAILS_REQUEST = "DEVICE_DETAILS_REQUEST";
export const DEVICE_DETAILS_SUCCESS = "DEVICE_DETAILS_SUCCESS";
export const DEVICE_DETAILS_FAIL = "DEVICE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
