export const ALL_DRUGCATEGORY_REQUEST = "ALL_DRUGCATEGORY_REQUEST";
export const ALL_DRUGCATEGORY_SUCCESS = "ALL_DRUGCATEGORY_SUCCESS";
export const ALL_DRUGCATEGORY_FAIL = "ALL_DRUGCATEGORY_FAIL";

export const ADMIN_DRUGCATEGORY_REQUEST = "ADMIN_DRUGCATEGORY_REQUEST";
export const ADMIN_DRUGCATEGORY_SUCCESS = "ADMIN_DRUGCATEGORY_SUCCESS";
export const ADMIN_DRUGCATEGORY_FAIL = "ADMIN_DRUGCATEGORY_FAIL";

export const NEW_DRUGCATEGORY_REQUEST = "NEW_DRUGCATEGORY_REQUEST";
export const NEW_DRUGCATEGORY_SUCCESS = "NEW_DRUGCATEGORY_SUCCESS";
export const NEW_DRUGCATEGORY_RESET = "NEW_DRUGCATEGORY_RESET";
export const NEW_DRUGCATEGORY_FAIL = "NEW_DRUGCATEGORY_FAIL";

export const UPDATE_DRUGCATEGORY_REQUEST = "UPDATE_DRUGCATEGORY_REQUEST";
export const UPDATE_DRUGCATEGORY_SUCCESS = "UPDATE_DRUGCATEGORY_SUCCESS";
export const UPDATE_DRUGCATEGORY_RESET = "UPDATE_DRUGCATEGORY_RESET";
export const UPDATE_DRUGCATEGORY_FAIL = "UPDATE_DRUGCATEGORY_FAIL";

export const DELETE_DRUGCATEGORY_REQUEST = "DELETE_DRUGCATEGORY_REQUEST";
export const DELETE_DRUGCATEGORY_SUCCESS = "DELETE_DRUGCATEGORY_SUCCESS";
export const DELETE_DRUGCATEGORY_RESET = "DELETE_DRUGCATEGORY_RESET";
export const DELETE_DRUGCATEGORY_FAIL = "DELETE_DRUGCATEGORY_FAIL";

export const DRUGCATEGORY_DETAILS_REQUEST = "DRUGCATEGORY_DETAILS_REQUEST";
export const DRUGCATEGORY_DETAILS_SUCCESS = "DRUGCATEGORY_DETAILS_SUCCESS";
export const DRUGCATEGORY_DETAILS_FAIL = "DRUGCATEGORY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
