export const ALL_DRUG_REQUEST = "ALL_DRUG_REQUEST";
export const ALL_DRUG_SUCCESS = "ALL_DRUG_SUCCESS";
export const ALL_DRUG_FAIL = "ALL_DRUG_FAIL";

export const ADMIN_DRUG_REQUEST = "ADMIN_DRUG_REQUEST";
export const ADMIN_DRUG_SUCCESS = "ADMIN_DRUG_SUCCESS";
export const ADMIN_DRUG_FAIL = "ADMIN_DRUG_FAIL";

export const NEW_DRUG_REQUEST = "NEW_DRUG_REQUEST";
export const NEW_DRUG_SUCCESS = "NEW_DRUG_SUCCESS";
export const NEW_DRUG_RESET = "NEW_DRUG_RESET";
export const NEW_DRUG_FAIL = "NEW_DRUG_FAIL";

export const UPDATE_DRUG_REQUEST = "UPDATE_DRUG_REQUEST";
export const UPDATE_DRUG_SUCCESS = "UPDATE_DRUG_SUCCESS";
export const UPDATE_DRUG_RESET = "UPDATE_DRUG_RESET";
export const UPDATE_DRUG_FAIL = "UPDATE_DRUG_FAIL";

export const DELETE_DRUG_REQUEST = "DELETE_DRUG_REQUEST";
export const DELETE_DRUG_SUCCESS = "DELETE_DRUG_SUCCESS";
export const DELETE_DRUG_RESET = "DELETE_DRUG_RESET";
export const DELETE_DRUG_FAIL = "DELETE_DRUG_FAIL";

export const DRUG_DETAILS_REQUEST = "DRUG_DETAILS_REQUEST";
export const DRUG_DETAILS_SUCCESS = "DRUG_DETAILS_SUCCESS";
export const DRUG_DETAILS_FAIL = "DRUG_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
